"""add_payment_id_to_yookassa

Revision ID: 16ed979cae3c
Revises: e7efa3ac6501
Create Date: 2024-11-23 21:22:04.553316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ed979cae3c'
down_revision: Union[str, None] = 'e7efa3ac6501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###
