"""fix_mapper_error3

Revision ID: 3d02771e3f14
Revises: 80e08e34ec97
Create Date: 2024-11-21 15:43:09.627096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d02771e3f14'
down_revision: Union[str, None] = '80e08e34ec97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
