"""fix_order_fields

Revision ID: c27a328998b4
Revises: 943a06d62da3
Create Date: 2024-11-21 10:08:14.322367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27a328998b4'
down_revision: Union[str, None] = '943a06d62da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order_subscription', ['id'])
    op.add_column('orders', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('orders', 'number_of_month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'number_of_month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'user_id')
    op.drop_constraint(None, 'order_subscription', type_='unique')
    # ### end Alembic commands ###
