"""add_columns_to_order

Revision ID: e7efa3ac6501
Revises: 95db63871bcf
Create Date: 2024-11-22 21:08:54.958029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7efa3ac6501'
down_revision: Union[str, None] = '95db63871bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('payment_url', sa.String(length=255), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('orders', 'payment_url')
    op.drop_column('orders', 'user_email')
    # ### end Alembic commands ###
