"""init

Revision ID: c7287889b986
Revises: 
Create Date: 2024-12-03 06:44:39.602220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7287889b986'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films_purchase_management',
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.Column('price', sa.DECIMAL(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('premiums_purchase_management',
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.Column('price', sa.DECIMAL(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('orders_film',
                    sa.Column('price', sa.DECIMAL(), nullable=False),
                    sa.Column('status', sa.String(length=255), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('user_email', sa.String(
                        length=255), nullable=True),
                    sa.Column('film_id', sa.UUID(), nullable=False),
                    sa.Column('payment_url', sa.String(
                        length=255), nullable=True),
                    sa.Column('payment_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('film_purchase_management_id',
                              sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['film_purchase_management_id'], [
                        'films_purchase_management.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('orders_premium',
                    sa.Column('total_price', sa.DECIMAL(), nullable=False),
                    sa.Column('status', sa.String(length=255), nullable=True),
                    sa.Column('number_of_month', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('user_email', sa.String(
                        length=255), nullable=True),
                    sa.Column('payment_url', sa.String(
                        length=255), nullable=True),
                    sa.Column('payment_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('premium_purchase_management_id',
                              sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['premium_purchase_management_id'], [
                        'premiums_purchase_management.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_premium')
    op.drop_table('orders_film')
    op.drop_table('premiums_purchase_management')
    op.drop_table('films_purchase_management')
    # ### end Alembic commands ###
